### ISSUE TITLE
Party crash with latest BQ

### ISSUE THREAD

**Issue by UnicorNora** [fonnymunkey/BQTweaker#1]

**Comment by fonnymunkey** [comment]
Crash report? Description? Etc?

**Comment by UnicorNora** [comment]
Crashes when clicking the party button,

https://pastebin.com/1aJyZk3V

**Comment by UnicorNora** [comment]
It seems to have a hard requirement on mobends which is not installed

**Comment by fonnymunkey** [comment]
Fallback check added in 1.3.3, mobends patch in config can also just be turned off if not using mobends.
