### ISSUE TITLE
Please make Embeds easier to use.

### ISSUE THREAD

**Issue by MagmaBro123** [fonnymunkey/BQTweaker#3]
Title.

I have tried using embes to no avail.

{Embed}TypeLink;https://the-betweenlands.fandom.com/wiki/The_Betweenlands_Wiki{Embed}, TypeLink;https://the-betweenlands.fandom.com/wiki/The_Betweenlands_Wiki{Embed}, etc all do and display nothing.

Allow pressing a 'Embed' button that pastes the correct stuff with the link in the correct area.

**Comment by fonnymunkey** [comment]
You are missing the width/height/text fields ex;
{Embed}TypeLink;<WebsiteLink>;<DisplayWidth>;<DisplayHeight>;<ButtonText>{Embed}

so in your case;

{Embed}TypeLink;https://the-betweenlands.fandom.com/wiki/The_Betweenlands_Wiki;64;16;The Betweenlands Wiki{Embed}

I have no current plans on updating BQTweaker outside of critical bugs as I no longer have dev environments setup for 1.12.2

**Comment by MagmaBro123** [comment]
Give the older versions to someone else.

Would be nice if embeds weren't as annoying to use.
