### ISSUE TITLE
[BQUT] View mode

### ISSUE THREAD

**Issue by Xetaxheb** [fonnymunkey/BQTweaker#5]
I'm conflicted because if really necessary one can still go into BQU's mod options and toggle it... but I'm not sure removing view mode button is a net benefit. In 1.12.2 era questing styles there's a fair bit of use to being able to see those. Maybe a config option like the quest list overrides? Or a config to just disable "always-hidden" from showing in view mode since that was the reason?

**Comment by fonnymunkey** [comment]
I disabled it because view mode shows always-hidden quests, as well as somewhat defeats the purpose of having secret quests, but apparently search mode also has the same issue and I don't believe I can change that on my side, so I may just end up making both toggleable in the bqut config.

**Comment by fonnymunkey** [comment]
Re-added view mode and added config options for both view mode and searching, off by default in v1.3.7.

**Comment by TFCAliarcy** [comment]
So just to clarify it isn't possible for quests marked as hidden to be hidden in view mode, but visible when in edit mode like in GTNH?

**Comment by fonnymunkey** [comment]
Quests are always visible when in edit mode, regardless of what visibility they are set to.
View mode and Search mode are not added by BQUTweaker, they are added by BQU, if you wanted it changed so their view mode and search mode does not show always-hidden quests you will need to make that suggestion to their Github.
I have no plans on trying to rewrite the modes outside of adding the ability to toggle the buttons on/off.
