### ISSUE TITLE
[BQU/T] Optifine causes rendering bugs

### ISSUE THREAD

**Issue by Xetaxheb** [fonnymunkey/BQTweaker#8]
Doubt this is fixable and it's a OF/BQ/U issue but... A simple test to see the problem is optifine G5 + BQU (+ BQUT) and DJ2's quest list (attached for convenience, renamed to .txt because github)

[DefaultQuests.txt](https://github.com/fonnymunkey/BQTweaker/files/12425597/DefaultQuests.txt)

Essentially, quests, chapters, and text will escape their confines... 
![image](https://github.com/fonnymunkey/BQTweaker/assets/3267055/012acccb-c259-4ff3-bbd0-f4f673bc3d25)
![image](https://github.com/fonnymunkey/BQTweaker/assets/3267055/0abc9973-30d7-4078-a9cc-a2fc927f360e)

**Comment by fonnymunkey** [comment]
I didn't have this issue when testing BQUT alongside Optifine G5, it may be one of the Optifine settings like fast math that breaks a lot of mods causing this.

Could you test replacing your optionsof.txt (Optifine settings) in the base install folder with this one:

[optionsof.txt](https://github.com/fonnymunkey/BQTweaker/files/12433939/optionsof.txt)

**Comment by Xetaxheb** [comment]
Fast render breaks it. There's also a weird inconsistency with "whether you have to restart client to fix or break" vs just toggling it... but anyway

**Comment by fonnymunkey** [comment]
Yea, Fast Render/Fast Math is a known offender of "break everything possible", I'm not sure if its really possible to fix, or worth the effort to try to find out in the first place. It breaks multiple other mods such as EnhancedVisuals, BetterFoliage, even just general shaders themselves.
