### ISSUE TITLE
[BQUT] Questlist override doesn't handle long or tall descriptions well

### ISSUE THREAD

**Issue by Xetaxheb** [fonnymunkey/BQTweaker#9]
This is an issue quest creators probably have to work with but since the description is moved from its own popout into the header bar, it can be cut off after a long sentence or so's worth of text.

I personally like the header format, but as this is clientsided (and therefore not necessarily accounted for by packmakers), it might be worth considering moving (or having an option for) description into it's own little box below chapters with its own scrolling if necessary. 

Would have to keep in mind (or fix) #8 (optifine breaking overlap) problems, but I don't think something like this would be too terrible
![image](https://github.com/fonnymunkey/BQTweaker/assets/3267055/fc91985b-82e7-4144-8c0a-547e559c30ce)

**Comment by fonnymunkey** [comment]
Added tooltips for both title and description, and added scrolling and a scrollbar to the description pane when its oversized in v1.3.7 to make it more apparent there is more text.
I may revist this and redesign it to be more like what you suggest, but for now I'm more satisfied with keeping it as a header with tooltip/scrollbar.
